export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";
export const CHANGE_BUN: "CHANGE_BUN" = "CHANGE_BUN";
export const MOVE_INGREDIENT: "MOVE_INGREDIENT" = "MOVE_INGREDIENT";
export const CLEAR_CONSTRUCTOR: "CLEAR_CONSTRUCTOR" = "CLEAR_CONSTRUCTOR";

export const SELECT_INGREDIENT: "SELECT_INGREDIENT" = "SELECT_INGREDIENT";
export const UNSELECT_INGREDIENT: "UNSELECT_INGREDIENT" = "UNSELECT_INGREDIENT";

export const GET_INGREDIENTS_REQUEST: "GET_INGREDIENTS_REQUEST" =
  "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_ERROR: "GET_INGREDIENTS_ERROR" =
  "GET_INGREDIENTS_ERROR";
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" =
  "GET_INGREDIENTS_SUCCESS";
export const INCREASE_INGREDIENT_COUNT: "INCREASE_INGREDIENT_COUNT" =
  "INCREASE_INGREDIENT_COUNT";
export const DECREASE_INGREDIENT_COUNT: "DECREASE_INGREDIENT_COUNT" =
  "DECREASE_INGREDIENT_COUNT";
export const CLEAR_INGREDIENTS_COUNT: "CLEAR_INGREDIENTS_COUNT" =
  "CLEAR_INGREDIENTS_COUNT";

export const POST_ORDER_REQUEST: "POST_ORDER_REQUEST" = "POST_ORDER_REQUEST";
export const POST_ORDER_ERROR: "POST_ORDER_ERROR" = "POST_ORDER_ERROR";
export const POST_ORDER_SUCCESS: "POST_ORDER_SUCCESS" = "POST_ORDER_SUCCESS";
export const CLOSE_ORDER: "CLOSE_ORDER" = "CLOSE_ORDER";

export const SIGN_UP: "SIGN_UP" = "SIGN_UP";
export const LOG_IN: "LOG_IN" = "LOG_IN";
export const LOG_OUT: "LOG_OUT" = "LOG_OUT";
export const SET_TOKEN: "SET_TOKEN" = "SET_TOKEN";
export const SET_USER: "SET_USER" = "SET_USER";
export const SET_CAN_RESET_PASSWORD: "SET_CAN_RESET_PASSWORD" =
  "SET_CAN_RESET_PASSWORD";

export const GET_ALL_ORDERS_REQUEST: "GET_ALL_ORDERS_REQUEST" =
  "GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_ERROR: "GET_ALL_ORDERS_ERROR" =
  "GET_ALL_ORDERS_ERROR";
export const GET_ALL_ORDERS_SUCCESS: "GET_ALL_ORDERS_SUCCESS" =
  "GET_ALL_ORDERS_SUCCESS";

export const SELECT_ORDER: "SELECT_ORDER" = "SELECT_ORDER";
export const UNSELECT_ORDER: "UNSELECT_ORDER" = "UNSELECT_ORDER";

export const GET_ORDERS_REQUEST: "GET_ORDERS_REQUEST" = "GET_ORDERS_REQUEST";
export const GET_ORDERS_ERROR: "GET_ORDERS_ERROR" = "GET_ORDERS_ERROR";
export const GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS" = "GET_ORDERS_SUCCESS";

export const WS_CONNECTION_START: "WS_CONNECTION_START" = "WS_CONNECTION_START";
export const WS_CONNECTION_CLOSED: "WS_CONNECTION_CLOSED" =
  "WS_CONNECTION_CLOSED";
